# -*- coding: utf-8 -*-
"""de_lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJOE_yLUk74NwoYEhClUEfEeXqZrQfEO
"""

#ZAD1
import pandas as pd
import json
df = pd.read_csv("proj1_ex01.csv")
print(df)

def get_dtype(series):
    if pd.api.types.is_integer_dtype(series):
        return "int"
    elif pd.api.types.is_float_dtype(series):
        return "float"
    else:
        return "other"

columns_info = []

for col in df.columns:
    col_info = {
        "name": col,
        "missing": df[col].isna().mean(),
        "type": get_dtype(df[col])
    }
    columns_info.append(col_info)

with open("proj_ex01_fields.json", "w") as f:
    json.dump(columns_info, f, indent=4)

#ZAD2

statistics = {}
for col in df.columns:
  if get_dtype(col) == "int" or get_dtype(col) == "float":
    stats = df[col].describe().to_dict()
  else:
    stats = {
            "count": int(df[col].count()),
            "unique": int(df[col].nunique()),
            "top": str(df[col].mode().iloc[0]) if not df[col].mode().empty else None,
            "freq": int(df[col].value_counts().iloc[0]) if not df[col].value_counts().empty else None
          }
  statistics[col] = stats

with open("proj1_ex02_stats.json", "w") as f:
    json.dump(statistics, f, indent=4)

print

#ZAD3

df.columns = (
    df.columns.str.replace(r"[^A-Za-z0-9_ ]", "", regex=True)
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

df.to_csv("proj1_ex03_columns.csv", index=False)

#ZAD4
df.to_excel("proj1_ex04_excel.xlsx", index=False)
df.to_json("proj1_ex04_json.json", orient="records", indent=4)
df.to_pickle("proj1_ex04_pickle.pkl")

#ZAD5
df_selected = df.iloc[:, 1:3]
df_selected = df_selected[df_selected.index.astype(str).str.startswith("v")]

df_selected.to_markdown("proj1_ex05_table.md", index=False)

#ZAD6

with open("proj1_ex06.json", "r") as f:
    data = json.load(f)

df_flat = pd.json_normalize(data)
df_flat.to_pickle("proj1_ex06_pickle.pkl")
